#baseURL = 'https://effie.io/'
languageCode = 'en'
theme = "JuiceBar"
title = "Effie's Blog"

[params]
author = "Effie Barak"
description = "Where I blog technical stuff and share my talks"
authorImage = "/images/author.jpeg"
paginate = 5

Title = "Effie's Blog"
content = "Hi, I'm Effie, an Android Expert and GDE, welcome to my blog!"
imageUrl = "/images/avatar.jpg"
# To add a new social icon (More social icons can be found in JuiceBar\layouts\partials\svg.html.)
[[params.social]]
name = "Github"
url = "https://github.com/coding-chick"
[[params.social]]
name = "speakerdeck"
url = "https://speakerdeck.com/codingchick"
[[params.social]]
name = "twitter"
url = "https://twitter.com/codingchick"
[[params.social]]
name = "mastodon"
url = "https://androiddev.social/@effie"
[[params.social]]
name = "email"
url = "mailto:efratbarak@gmail.com"

[taxonomies]
category = "categories"

# To add a new navigation link
[[menu.main]]
name = "About"
url = "/about"
[[menu.main]]
name = "Blog"
url = "/post"       

# Used for outputting the documentation (required).
[outputs]
home = ["HTML", "RSS", "JSON"]



